# Generated by Django 4.1.1 on 2022-09-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_digest', models.CharField(max_length=120)),
                ('affiliation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(max_length=28)),
                ('strand', models.CharField(choices=[('+', 'forward'), ('-', 'reverse')], default='+', max_length=10)),
                ('cas', models.CharField(max_length=20)),
                ('efficiency', models.FloatField()),
                ('percent_gc', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_guides', to='noucleus_db.gene')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guides', to='noucleus_db.gene')),
            ],
        ),
    ]
