# Generated by Django 4.1.1 on 2022-09-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noucleus_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='image_ref',
            field=models.TextField(null=True),
        ),
    ]
