# Generated by Django 4.1.1 on 2022-09-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noucleus_db', '0002_gene_image_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guides', to='noucleus_db.user'),
        ),
    ]
