# Generated by Django 4.1.1 on 2022-09-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noucleus_db', '0003_alter_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='edit_type',
            field=models.CharField(choices=[('disruption', 'disruption'), ('deletion', 'deletion'), ('insertion', 'insertion'), ('correction', 'correction')], default='disruption', max_length=20),
        ),
    ]
